include: package:flutter_lints/flutter.yaml

linter:

  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_setters_without_getters: true
    cascade_invocations: true
    eol_at_end_of_file: true
    prefer_single_quotes: true
    prefer_final_locals: true
    sized_box_shrink_expand: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    overridden_fields: false
    avoid_print: true