name: riverpod_movie_example
description: A new Flutter project for using riverpod.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2

flutter:

  uses-material-design: true

  assets:
     - data/
